author = "Tobias Lindberg"
keywords = "tobias lindberg,tobias ehlert,ehlert,consultant,senior consultant,developer"

avatarurl = "images/avatar.jpg"
# gravatar = "tobias.ehlert@gmail.com"

dateformat = "2006-01-02 15:04"
colorscheme = "auto"
hidecredits = false
hidecopyright = false
rtl = false
since = 2019
math = true
customCSS = ["css/custom.css", "css/icomoon.css"]

# Social links
[[social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin-square"
    weight = 1
    url = "https://www.linkedin.com/in/ehlerttobias/"
    rel = "noreferrer"
    target = "_blank"
[[social]]
    name = "Instagram"
    icon = "fa fa-2x fa-instagram"
    weight = 2
    url = "https://instagram.com/ehlerttobias/"
    rel = "noreferrer"
    target = "_blank"
[[social]]
    name = "Facebook"
    icon = "fa fa-2x fa-facebook-square"
    weight = 3
    url = "https://facebook.com/tysken"
    rel = "noreferrer"
    target = "_blank"
[[social]]
    name = "Twitter"
    icon = "fa fa-2x fa-twitter"
    weight = 4
    url = "https://twitter.com/EhlertTobias/"
    rel = "noreferrer"
    target = "_blank"
[[social]]
    name = "GitHub"
    icon = "fa fa-2x fa-x-github"
    weight = 5
    url = "https://github.com/tobiasehlert/"
    rel = "noreferrer"
    target = "_blank"
[[social]]
    name = "DigitalOcean"
    icon = "fa fa-2x fa-digital-ocean"
    weight = 6
    url = "https://m.do.co/c/452a006a298d"
    rel = "noreferrer"
    target = "_blank"
[[social]]
    name = "Tesla"
    icon = "fa fa-2x icon-tesla"
    weight = 7
    url = "https://ts.la/tobias85122"
    rel = "noreferrer"
    target = "_blank"