baseURL = "https://tobiasehlert.github.io/"
title = "TobiasEhlert.github.io"

publishdir = "tobiasehlert.github.io"

[params]
    footercontent = "This page is hosted on GitHub Pages - Full page at https://tobiaslindberg.com"
    hidecredits = false
    hidecopyright = false
